# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ishwarsawale.github.io
title: Ishwar Sawale
subtitle: Tech tutorials and other tidbits
author: Ishwar Sawale
simple_search: https://www.duckduckgo.com/
description: Ishwar  writes about technology and Web development.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
# subscribe_rss: http://feeds.feedburner.com/jhabdas
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: category
tag_dir: tag
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, custom/asides/about.html, custom/asides/twitter_octo.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides: [custom/asides/about.html, asides/recent_posts.html, custom/asides/blogroll.html]
post_asides: [custom/asides/adsense_sidebar.html, asides/recent_posts.html, asides/github.html, custom/asides/blogroll.html]
# page_asides:

# ----------------------- #
#    Custom Settings      #
# ----------------------- #

blogroll: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: jhabdas
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: jhabdas
twitter_widget_id: 382004356658130944
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 103260084358483831085
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: habdas
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-6473963-1

# Facebook Like
facebook_like: false

# Flickr (for Local testing only - DO NOT commit with actual secret)
# flickr:
#   api_key:
#   shared_secret:

# prose.io settings
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 'source/_posts'
  siteurl: 'https://ishwarsawale.github.io'
  media: 'assets'
  metadata:
    source/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          label: "Author"
          value: "Josh Habdas"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Post Title"
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "categories"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Create or choose"
          alterable: true
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
